### ISSUE TITLE
Error when upgrading from 0.5.4 to 0.6.2

### ISSUE THREAD

**Issue by tapufd** [bakito/adguardhome-sync#281] opened 2024-01-17 16:34 UTC
### What happened?

Using in docker a config-file -> CONFIGFILE=/config/adguardhome-sync.yaml
All works in v0.5.4, but when upgrading my docker image to v0.6.2, adguardhome-sync doesn't start.
See attached log-file...
[_adguardhome-sync_logs.txt](https://github.com/bakito/adguardhome-sync/files/13965927/_adguardhome-sync_logs.txt)

### AdguardHome-Sync Version

current = 0.5.4
target = 0.6.2

### AdguardHome Version

v0.107.43

### Configuration

```shell
# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "0 * * * *"

# runs the synchronisation on startup
runOnStart: false

origin:
  # url of the origin instance
  url: https://192.168.1.2:3443
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username: xxx
  password: 'xxx'

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: https://192.168.1.3:3443
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username: xxx
  password: 'xxx'
  interfaceName: eth0
  dhcpServerEnabled: false

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8585
  # if username and password are defined, basic auth is applied to the sync API 
  username: xxx
  password: 'xxx'

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
```

### Relevant log output

```shell
See attached log...
```

**Comment by bakito** [comment] 2024-01-17 17:37
Hi @tapufd 

Can you please switch to array replicas config? 
```
# replicas instances
replicas:
  - url: http://192.168.1.3
    username: username
    password: password
```

**Comment by bakito** [comment] 2024-01-17 17:50
Update, the issue seems to be with `dhcpServerEnabled: false` it also happens wit array config.

**Comment by tapufd** [comment] 2024-01-17 17:51
Seems I already was using the "replicas" notation.

**Comment by bakito** [comment] 2024-01-17 18:52
@tapufd can you try the newest main image and check if the issue is solved?
https://github.com/bakito/adguardhome-sync/pkgs/container/adguardhome-sync/168115720?tag=main

**Comment by tapufd** [comment] 2024-01-18 17:56
Hi, tested the latest main image/pkg **ghcr.io/bakito/adguardhome-sync:main** and that one works.
Did a sync, and all seems to be working.
Thx!

**Comment by bakito** [comment] 2024-01-18 20:09
released with https://github.com/bakito/adguardhome-sync/releases/tag/v0.6.3

**Closed by bakito** 2024-01-18 20:09 UTC
