### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by nknab** [bakito/adguardhome-sync#78] opened 2022-06-12 11:35 UTC
**Describe the bug**
When I start the docker container, it does not connect and produces a 403 Error.

**To Reproduce**
1. What version of AdGuardHome sync used?
    `v0.4.3`

2. What version of AdGuardHome us used?
    `v0.108.0-b.9`

3. How does the configuration look?
`cron: "*/1 * * * *"

origin:
  url: http://192.168.0.140:9970
  insecureSkipVerify: true
  username: username
  password: password

replica:
  url: http://192.168.0.141:9970
  insecureSkipVerify: true
  username: username
  password: password

api:
  port: 9080
  username: username
  password: password`

4. What is the error message?
 `Error getting origin status	{"from": "192.168.0.140:9970", "error": "403 Forbidden"}`

**Expected behavior**
 - I expected the files to sync across.

Log Files
`-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-06-12T12:56:10.665+0200	INFO	root	cmd/root.go:114	Using config file:/config/adguardhome-sync.yaml
2022-06-12T12:56:10.668+0200	INFO	sync	sync/sync.go:30	AdGuardHome sync	{"version": "0.4.3", "build": "2022-02-14T17:40:34Z"}
2022-06-12T12:56:10.669+0200	INFO	sync	sync/sync.go:50	Setup cronjob	{"cron": "*/1 * * * *"}
2022-06-12T12:56:10.669+0200	INFO	sync	sync/http.go:54	Starting API server	{"port": 9080}
2022-06-12T12:56:10.669+0200	INFO	sync	sync/sync.go:60	Running sync on startup
2022-06-12T12:56:10.670+0200	DEBUG	client	client/client.go:126	do get	{"host": "192.168.0.140:9970", "method": "GET", "path": "status"}
2022-06-12T12:56:10.673+0200	DEBUG	client	client/client.go:138	got response	{"host": "192.168.0.140:9970", "method": "GET", "path": "status", "status": 403, "body": "Forbidden"}
2022-06-12T12:56:10.673+0200	ERROR	sync	sync/sync.go:99	Error getting origin status	{"from": "192.168.0.140:9970", "error": "403 Forbidden"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:99
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:61
`

**Comment by BartKoppers** [comment] 2022-06-12 21:52
Please share your /config/adguardhome-sync.yaml

**Comment by nknab** [comment] 2022-06-12 22:11
> Please share your /config/adguardhome-sync.yaml
The Config file is in the issue above but here it is:
cron: "*/1 * * * *"

origin:
url: http://192.168.0.140:9970/
insecureSkipVerify: true
username: username
password: password

replica:
url: http://192.168.0.141:9970/
insecureSkipVerify: true
username: username
password: password

api:
port: 9080
username: username
password: password

**Comment by bakito** [comment] 2022-06-20 16:43
@nknab I was not able to reproduce this issue.

Do you see any errors in  the logs of your origin instance?

Is the origin instance setup correctly?

Are passwords correct.

**Comment by bakito** [comment] 2022-07-24 16:25
closing, since there's no update

**Closed by bakito** 2022-07-24 16:25 UTC
